version: '2'

services:
  proxy:
        build: ./src
        image: myproxy
        container_name: myproxy
        command: bash -c "./run.sh"
        volumes:
          - ./src:/src
          - ./logs:/var/log/erss
        ports:
          - "12345:12345"
    